TestingEdits -- Snooze inputs visibility, and checkbox tick positioning
subsbase/notification-center pull request #91
Opened 2023-09-12 08:08 UTC by Saraahmedd

2023-09-12 10:46 UTC, Ibrahimogod requested changes

2023-09-12 10:46 UTC, Ibrahimogod commented on frontend/src/components/NotificationList.vue
> +  currentsnoozeIndex.value = -1
we have camel case convention 'currentSnoozeIndex'

2023-09-12 10:46 UTC, Ibrahimogod commented on frontend/src/components/NotificationList.vue
> +  currentsnoozeIndex.value = -1
we have camel case convention 'currentSnoozeIndex'

2023-09-13 09:25 UTC, fahdarafat approved these changes

2023-09-13 09:27 UTC, merged